name: HOTEL DEPLOYMENT

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  job1:
    runs-on: ["self-hosted", "hotel"]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Clear existing site (optional but clean)
        run: sudo rm -rf /var/www/hotel/html/*

      - name: Copy project to web root
        run: sudo cp -r . /var/www/hotel/html/

      - name: Set correct permissions
        run: sudo chown -R www-data:www-data /var/www/hotel/html

      - name: Reload Nginx
        run: sudo systemctl reload nginx

